$('#game-difficulty').append('<option value="4">CLASSIC NORMAL</option>'+
                      '<option value="5">CLASSIC HARD</option>'+
                      '<option value="6">CLASSIC RELENTLESS</option>'+
                      '<option value="7">CLASSIC ABSURD</option>'+
                      '<option value="8">SMART</option>')

requireGW(['shared/gw_balance'], function(balance) {
  balance.difficultyInfo.push(
    {
      // classic normal
      percent_vehicle: 0.55,
      percent_bot: 0.25,
      percent_air: 0.1,
      percent_naval: 0.075,
      percent_orbital: 0.025,
      rampDifficulty: true,
      adv_eco_mod: 3.0,
      adv_eco_mod_alone: 2.5,
      goForKill: false,
      microType: 0,
      neuralDataMod: 1.75,
      mandatoryMinions: 0,
      minionMod: 0,
      bossDemandCheckMod: 1.75,
      priority_scout_metal_spots: false,
      useEasierSystemTemplate: false,
      factory_build_delay_min: 12,
      factory_build_delay_max: 20,
      unable_to_expand_delay: 300,
      per_expansion_delay: 1200,
      enable_commander_danger_responses: false,
      fabber_to_factory_ratio_basic: 5.0,
      fabber_to_factory_ratio_advanced: 1.0,
      fabber_alone_on_planet_mod: 1.0,
      basic_to_advanced_factory_ratio: 0,
      factory_alone_on_planet_mod: 1.0,
      min_basic_fabbers: 8,
      max_basic_fabbers: 15,
      min_advanced_fabbers: 3,
      max_advanced_fabbers: 20,
      personality_tags:
      [
        "SlowerExpansion"
      ],
      econBase: 0.38,
      econRatePerDist: 0.03,
      metalDrainCheck: 0.44,
      metalDrainCheckPerDist: 0.000,
      metalDemandCheck: 0.55,
      metalDemandCheckPerDist: 0.000,
      energyDrainCheck: 0.61,
      energyDrainCheckPerDist: 0.000,
      energyDemandCheck: 0.7,
      energyDemandCheckPerDist: 0.000
    },
    {
      // classic hard
      percent_vehicle: 0.45,
      percent_bot: 0.25,
      percent_air: 0.2,
      percent_naval: 0.05,
      percent_orbital: 0.05,
      rampDifficulty: true,
      adv_eco_mod: 1.7,
      adv_eco_mod_alone: 1.7,
      goForKill: true,
      microType: 1,
      neuralDataMod: 1.25,
      mandatoryMinions: 0,
      minionMod: 0.75,
      bossDemandCheckMod: 1.25,
      priority_scout_metal_spots: false,
      useEasierSystemTemplate: false,
      factory_build_delay_min: 5,
      factory_build_delay_max: 8,
      unable_to_expand_delay: 0,
      enable_commander_danger_responses: false,
      per_expansion_delay: 120,
      fabber_to_factory_ratio_basic: 1.5,
      fabber_to_factory_ratio_advanced: 1.0,
      fabber_alone_on_planet_mod: 2.0,
      basic_to_advanced_factory_ratio: 0,
      factory_alone_on_planet_mod: 0.5,
      min_basic_fabbers: 1,
      max_basic_fabbers: 8,
      min_advanced_fabbers: 3,
      max_advanced_fabbers: 20,
      personality_tags:
      [
        "PreventsWaste"
      ],
      econBase: 0.75,
      econRatePerDist: 0.07,
      metalDrainCheck: 0.44,
      metalDrainCheckPerDist: 0.000,
      metalDemandCheck: 0.55,
      metalDemandCheckPerDist: 0.000,
      energyDrainCheck: 0.61,
      energyDrainCheckPerDist: 0.000,
      energyDemandCheck: 0.7,
      energyDemandCheckPerDist: 0.000
    },
    {
      // classic relentless
      percent_vehicle: 0.45,
      percent_bot: 0.25,
      percent_air: 0.2,
      percent_naval: 0.05,
      percent_orbital: 0.05,
      rampDifficulty: true,
      adv_eco_mod: 1.2,
      adv_eco_mod_alone: 0.95,
      goForKill: true,
      microType: 2,
      neuralDataMod: 1.0,
      mandatoryMinions: 0,
      minionMod: 1,
      bossDemandCheckMod: 1.0,
      priority_scout_metal_spots: true,
      useEasierSystemTemplate: false,
      factory_build_delay_min: 0,
      factory_build_delay_max: 0,
      unable_to_expand_delay: 0,
      enable_commander_danger_responses: true,
      per_expansion_delay: 0,
      fabber_to_factory_ratio_basic: 1.5,
      fabber_to_factory_ratio_advanced: 1.0,
      fabber_alone_on_planet_mod: 2.0,
      basic_to_advanced_factory_ratio: 0,
      factory_alone_on_planet_mod: 0.5,
      min_basic_fabbers: 1,
      max_basic_fabbers: 8,
      min_advanced_fabbers: 3,
      max_advanced_fabbers: 20,
      personality_tags:
      [
        "PreventsWaste"
      ],
      econBase: 1.13,
      econRatePerDist: 0.1,
      metalDrainCheck: 0.44,
      metalDrainCheckPerDist: 0.000,
      metalDemandCheck: 0.55,
      metalDemandCheckPerDist: 0.000,
      energyDrainCheck: 0.61,
      energyDrainCheckPerDist: 0.000,
      energyDemandCheck: 0.7,
      energyDemandCheckPerDist: 0.000
    },
    {
      // classic absurd
      percent_vehicle: 0.45,
      percent_bot: 0.25,
      percent_air: 0.2,
      percent_naval: 0.05,
      percent_orbital: 0.05,
      adv_eco_mod: 1.3,
      adv_eco_mod_alone: 0.85,
      goForKill: true,
      microType: 2,
      neuralDataMod: 1.0,
      mandatoryMinions: 1,
      minionMod: 1,
      bossDemandCheckMod: 1.0,
      priority_scout_metal_spots: true,
      useEasierSystemTemplate: false,
      unable_to_expand_delay: 0,
      enable_commander_danger_responses: true,
      per_expansion_delay: 0,
      fabber_to_factory_ratio_basic: 1.5,
      fabber_to_factory_ratio_advanced: 1.0,
      fabber_alone_on_planet_mod: 2.0,
      basic_to_advanced_factory_ratio: 0,
      factory_alone_on_planet_mod: 0.5,
      min_basic_fabbers: 1,
      max_basic_fabbers: 15,
      min_advanced_fabbers: 3,
      max_advanced_fabbers: 50,
      personality_tags:
      [
        "PreventsWaste"
      ],
      econBase: 2.0,
      econRatePerDist: 0.01,
      metalDrainCheck: 0.44,
      metalDrainCheckPerDist: 0.000,
      metalDemandCheck: 0.55,
      metalDemandCheckPerDist: 0.000,
      energyDrainCheck: 0.61,
      energyDrainCheckPerDist: 0.000,
      energyDemandCheck: 0.7,
      energyDemandCheckPerDist: 0.000
    },
    {
      // smart
      percent_vehicle: 0.45,
      percent_bot: 0.25,
      percent_air: 0.2,
      percent_naval: 0.05,
      percent_orbital: 0.05,
      rampDifficulty: true,
      adv_eco_mod: 1.3,
      adv_eco_mod_alone: 0.85,
      goForKill: true,
      microType: 2,
      neuralDataMod: 1.0,
      mandatoryMinions: 0,
      minionMod: 1,
      bossDemandCheckMod: 1.0,
      priority_scout_metal_spots: true,
      useEasierSystemTemplate: false,
      unable_to_expand_delay: 0,
      enable_commander_danger_responses: true,
      per_expansion_delay: 0,
      fabber_to_factory_ratio_basic: 1.5,
      fabber_to_factory_ratio_advanced: 1.0,
      fabber_alone_on_planet_mod: 2.0,
      basic_to_advanced_factory_ratio: 0,
      factory_alone_on_planet_mod: 0.5,
      min_basic_fabbers: 1,
      max_basic_fabbers: 15,
      min_advanced_fabbers: 3,
      max_advanced_fabbers: 50,
      personality_tags:
      [
        "PreventsWaste"
      ],
      econBase: 0.75,
      econRatePerDist: 0.07,
      metalDrainCheck: 0.44,
      metalDrainCheckPerDist: 0.005,
      metalDemandCheck: 0.55,
      metalDemandCheckPerDist: 0.006,
      energyDrainCheck: 0.61,
      energyDrainCheckPerDist: 0.005,
      energyDemandCheck: 0.7,
      energyDemandCheckPerDist: 0.006,
    }
  )
})
